Import("env")

env.Append(CPPPATH = ["../../../include/", "../../../../include/informer/"])
env.Append(CCFLAGS = ["-W", "-Wall", "-DAesalonCollector", "-D_GNU_SOURCE"])
env.Append(LIBS = ["rt", "dl"])

env.SharedLibrary(target="collector", source=Glob("collector/*.c"))

