sources = Glob("*.c", strings=True) + Glob("*.cpp", strings=True)

Import("env")

testsEnv = env.Clone()

testsEnv.Append(LIBS = ["rt"])

for test in sources:
	targetName = test.split(".")[0]
	env.Program(target = targetName, source = test)
