import sys
import subprocess

Import("qtEnv")

env = qtEnv

env.Replace(QT4_MOCHSUFFIX = ".cpp")
env.Replace(QT4_MOCHPREFIX = "../../visualizer/build/moc_")

env.EnableQt4Modules(["QtCore", "QtGui", "QtNetwork"])

visualizerIncludePath = env.Dictionary()["includeRoot"] + "/visualizer"

env.Append(CPPPATH = [visualizerIncludePath])
env.Append(CCFLAGS = ["-W", "-Wall", "-g", "-DAesalonVisualizer"])

sourceFiles = Glob("*.cpp", strings=True) + Glob("*/*.cpp", strings=True)

env.Program(target = "aesalon_visualizer", source = sourceFiles)
