Import("env")

env.Append(CPPPATH = ["../../include/", "../../include/monitor/"])
env.Append(CCFLAGS = ["-W", "-Wall", "-g", "-DAesalonMonitor"])

env.Program(target = "aesalon", source = Glob("*.cpp") + Glob("*/*.cpp"))
