Import("env")
Import("qtEnv")
"""
dirglob = Glob("*/SConscript", strings=True)

# Construct linking path first . . .
for path in dirglob:
	dirname = path[:path.find('/')]
	env.Append(LIBPATH = ["#.build/" + dirname])
	qtEnv.Append(LIBPATH = ["#.build/" + dirname])

for path in dirglob:
	SConscript(path)"""

dirs = "util config storage artisan monitor visualizer".split()

for dir in dirs:
	env.Append(LIBPATH="#.build/" + dir)
	qtEnv.Append(LIBPATH="#.build/" + dir)

SConscript(dirs=dirs)
