Import("env")
Import("qtEnv")

dirglob = Glob("*/SConscript", strings=True)

# Construct linking path first . . .
for path in dirglob:
	dirname = path[:path.find('/')]
	env.Append(LIBPATH = ["#.build/" + dirname])
	qtEnv.Append(LIBPATH = ["#.build/" + dirname])

for path in dirglob:
	SConscript(path)
