Import("env")

monitorEnv = env.Clone()

monitorEnv.Append(LINKFLAGS = ["-rdynamic"])
monitorEnv.Append(LINKFLAGS = ["-Xlinker", "--whole-archive", "-laesalon-config", "-laesalon-util", "-laesalon-storage", "-Xlinker", "--no-whole-archive"])
monitorEnv.Append(LIBS = ["rt", "dl"])

monitor = monitorEnv.Program(target = "aesalon", source = Glob("*.cpp") + Glob("*/*.cpp"))

Import(["util", "config", "storage"])
Depends(monitor, [util, config, storage])

